[0m17:43:22.762014 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D63356C920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D63354F7A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D633E36CF0>]}


============================== 17:43:22.765086 | 2a2d79d0-7e0f-49c5-85a7-cf72c0ef0fcc ==============================
[0m17:43:22.765086 [info ] [MainThread]: Running with dbt=1.10.5
[0m17:43:22.765086 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\strol\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init ecommerce_dbt', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:43:22.781122 [info ] [MainThread]: Creating dbt configuration folder at C:\Users\strol\.dbt
[0m17:43:22.784414 [debug] [MainThread]: Starter project path: C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m17:43:22.796285 [info ] [MainThread]: 
Your new dbt project "ecommerce_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:43:22.796808 [info ] [MainThread]: Setting up your profile.
[0m17:46:03.208122 [error] [MainThread]: Encountered an error:

[0m17:46:03.212049 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 128, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 483, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 168, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m17:46:03.214063 [debug] [MainThread]: Command `dbt init` failed at 17:46:03.214063 after 160.61 seconds
[0m17:46:03.215061 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D6340DEBD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D635A160C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D63452A4E0>]}
[0m17:46:03.216063 [debug] [MainThread]: Flushing usage events
[0m17:46:03.856894 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:46:19.249912 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021ADEDF8A40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021ADEF447A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021ADEC2BA70>]}


============================== 17:46:19.254058 | 022faf49-a653-4b74-acb3-f24cd5a8bb30 ==============================
[0m17:46:19.254058 [info ] [MainThread]: Running with dbt=1.10.5
[0m17:46:19.255058 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\strol\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt init ecommerce_dbt', 'send_anonymous_usage_stats': 'True'}
[0m17:46:19.271225 [info ] [MainThread]: A project called ecommerce_dbt already exists here.
[0m17:46:19.272229 [debug] [MainThread]: Command `dbt init` succeeded at 17:46:19.272229 after 0.24 seconds
[0m17:46:19.272229 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021ADEDF8A40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021ADF36CE30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021ADEBAF7D0>]}
[0m17:46:19.273227 [debug] [MainThread]: Flushing usage events
[0m17:46:19.888794 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:46:50.016067 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196B2404140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196B534B9E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196B534BB60>]}


============================== 17:46:50.020158 | 949f0222-3eb7-49d8-848a-be3431f0a505 ==============================
[0m17:46:50.020158 [info ] [MainThread]: Running with dbt=1.10.5
[0m17:46:50.020158 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\strol\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt init ecommerce_dbt', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:46:50.037907 [debug] [MainThread]: Starter project path: C:\Users\strol\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m17:46:50.050916 [info ] [MainThread]: 
Your new dbt project "ecommerce_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:46:50.050916 [info ] [MainThread]: Setting up your profile.
[0m17:51:09.020996 [info ] [MainThread]: Profile ecommerce_dbt written to C:\Users\strol\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m17:51:09.022016 [debug] [MainThread]: Command `dbt init` succeeded at 17:51:09.022016 after 259.15 seconds
[0m17:51:09.023003 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196B2404140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196B54AB530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196AF944920>]}
[0m17:51:09.023003 [debug] [MainThread]: Flushing usage events
[0m17:51:09.637354 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:02:31.835735 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3A426D190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3A20535F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3A3701010>]}


============================== 13:02:31.840247 | bbe19f77-38e7-4b56-8704-3b83f59a14be ==============================
[0m13:02:31.840247 [info ] [MainThread]: Running with dbt=1.10.5
[0m13:02:31.841247 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\strol\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:02:31.841755 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\strol\OneDrive\Documentos\DE_Henry\Proyecto_Integrador_M2_DE_FS\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:02:31.843255 [debug] [MainThread]: Command `dbt run` failed at 13:02:31.843255 after 0.18 seconds
[0m13:02:31.843754 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3A4AAB8F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3A4A8F560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3A20535F0>]}
[0m13:02:31.844254 [debug] [MainThread]: Flushing usage events
[0m13:02:32.500709 [debug] [MainThread]: An error was encountered while trying to flush usage events
